
@hots = http://localhost:8081
// We can use this to check if the meal is vegan or vegetarian

@is_vegan = true
@is_vegetarian = true

GET {{hots}}/listMeals?is_vegan={{is_vegan}}&is_vegetarian={{is_vegetarian}}

